<?php

return [
    "api_debug" => env("API_DEBUG", false),
    "google_api_key" => unlock(env("GOOGLE_API_KEY")),
    "google_language_api_key" => unlock(env("GOOGLE_LANGUAGE_API_KEY")),
    "short_name" => "AGRI",
    "name" => "AgriApp",
    "qr_code_url" => "https://newagriapp.s3.ap-south-1.amazonaws.com/qrcode.jpg",
    "default_order_mail"=>"agpsales@gmail.com",
    "backend_url" => "agiadm",
    "secret_key" => "402620C92552D9303C58B901B43B0A41718E772C19520DD9A9AA52CE5A8FCB99",
    "slug_format" => "/[^A-Za-z0-9-]+/",
    "prefix" => "agri_",
    "prakshep" => env("PRAKSHEP_NAME", "agri_farm_"),
    "prakshep_secret_key" => "b0020b42-cce3-424d-9bf3-bc4f1c835a40",
    "prakshep_company_id" => "CR002",
    "version" => "v=" . time(),
    "password_format" => "/^(?=.*?[A-Za-z0-9]).{6,}$/",
    "password_message" => "Password should be minimum 6 characters long.",
    "dummy_distance" => env("DUMMY_DISTANCE", false),
    "default_image" => "/default/600x600.jpg",
    "msg91" => [
        "template_id" => unlock(env("MSG_91_TEMPLATE_ID")),
        "auth_key" => unlock(env("MSG_91_AUTH_KEY")),
    ],
    "insta_mojo" => [
        "api_version" => unlock(env("INSTA_MOJO_API_VERSION")),
        "api_key" => unlock(env("INSTA_MOJO_API_KEY")),
        "auth_token" => unlock(env("INSTA_MOJO_AUTH_TOKEN")),
        "salt" => unlock(env("INSTA_MOJO_SALT")),
        "client_id" => unlock(env("INSTA_MOJO_CLIENT_ID")),
        "client_secret" => unlock(env("INSTA_MOJO_CLIENT_SECRET")),
        "payment_processing_in_app" => (int) unlock(env("INSTA_MOJO_PROCESS_IN_APP")),
        "api_url_v1_1" => ((int) unlock(env("INSTA_MOJO_SANDBOX")) == 0) ? "https://www.instamojo.com/api/1.1" : "https://test.instamojo.com/api/1.1",
        "api_url_v2" => ((int) unlock(env("INSTA_MOJO_SANDBOX")) == 0) ? "https://api.instamojo.com" : "https://test.instamojo.com",
    ],
    "razorpay" => [
        "api_key" => unlock(env("RAZORPAY_API_KEY")),
        "api_secret" => unlock(env("RAZORPAY_API_SECRET")),
        "api_url" => "https://api.razorpay.com/v1"
    ],
    "ship_rocket" => [
        "api_url" => "https://apiv2.shiprocket.in",
        "api_user_name" => unlock(env("SHIP_ROCKET_API_USER")),
        "api_password" => unlock(env("SHIP_ROCKET_PASSWORD")),
        'track_base_url'=>'https://apiv2.shiprocket.in/v1/external/courier/track/awb/'
    ],

      "ecomexpress" => [
        "api_url" => "https://api.ecomexpress.in/apiv2/",
        "username" => unlock(env("ecomexpress_username")),
        "password" => unlock(env("ecomexpress_password")),
        'track_base_url'=>'https://plapi.ecomexpress.in/track_me/api/mawbd/'
    ],
    "pickrr" => [
        "api_url" => "https://pickrr.com/api/",
        'track_base_url'=>'https://async.pickrr.com/track/tracking/',
        'api_key'=>'18057d9af6adaa3685a879318d709fd3826508'
    ],
    "firebase" => [
        "topic_prefix" => env('FIREBASE_TOPIC_PREFIX', ''),
        "create_topic_url" => "https://iid.googleapis.com/iid/v1:batchAdd",
        "remove_topic_url" => "https://iid.googleapis.com/iid/v1:batchRemove",
        "notification_url" => "https://fcm.googleapis.com/fcm/send",
        "validate_fcm_url" => "https://iid.googleapis.com/iid/info",
        "server_key" => env('FIREBASE_SERVER_KEY', '')
    ],

    "device_type" => "1,2,3",
    "upload_limit" => 'Maximum allowed file size is 3 MB',
    "upload_video_limit" => 'Maximum allowed file size is 50 MB',
    "upload_doc_limit" => 'Maximum allowed file size is 5 MB',
    "upload_limit_size" => 1024*3,
    "upload_video_limit_size" => 1024*50,
    "upload_doc_limit_size" => 1024*5,
    "device_type_desc" => "1: Web, 2: iOS, 3: Android",
    "device_name" => [
        1 => "Web",
        2 => "iOS",
        3 => "Android",
    ],
    "opt_valid_for_sec" => 300,
    "otp_time_limit" => 300,
    "referal_prefix" => "AGRI",
    "skip_id" => "Send back the last id recieved, Start with 0, Stop when continue is returned as 0",
    "skip_x_record" => "Skip X records.<br/>Start with 0<br/>Stop when skip is returned as -1",
    "take_x_record" => "Get X records",
    "prevent_duplicate_for_x_min" => 1,
    "prevent_duplicate_message" => "Request already in progress. Please try after 1 min.",
    "currency" => "INR",

    "profile_img" => ["width" => 200, "height" => 200],
    "disease_img" => ["width" => 600, "height" => 600],
    "product_category_img" => ["width" => 600, "height" => 600],
    "product_img" => ["width" => 700, "height" => 1000],
    "flag_img" => ["width" => 50, "height" => 30],
    "manufacture_img" => ["width" => 600, "height" => 600],
    "crop_category_img" => ["width" => 600, "height" => 600],
    "crop_img" => ["width" => 600, "height" => 600],
    "crop_calendar_img" => ["width" => 600, "height" => 600],
    "service_img" => ["width" => 50, "height" => 50],
    "plan_img" => ["width" => 780, "height" => 600],
    "splash_screen_image_img" => ["width" => 780, "height" => 970],
    "pop_img" => ["width" => 800, "height" => 600],
    "pop_lesson_content_img" => ["width" => 660, "height" => 500],
    "content_category_img" => ["width" => 600, "height" => 600],
    "blog_img" => ["width" => 570, "height" => 600],
    "news_img" => ["width" => 570, "height" => 600],
    "news_content_img" => ["width" => 730, "height" => 480],
    "community_img" => ["width" => 700, "height" => 460],
    "login_image_img" => ["width" => 630, "height" => 500],
    "banner_img" => ["width" => 780, "height" => 300],
    "banner_content_img" => ["width" => 700, "height" => 460],
    "share_coupon_img" => ["width" => 700, "height" => 460],
    "campaign_image" => ["width" => 500, "height" => 530],
    "hidden_image" => ["width" => 500, "height" => 530],
    "offer_mappings"=>[
        "specials"=>5,
        "combo"=>4,
        "bogo"=>3,
        "offers"=>2
    ],
    "offer_mappings_text"=>[
        "specials"=> "SPECIALS",
        "combo"=>'COMBO',
        "bogo"=>"BOGO",
    ],
    "banner" => [
        1 => "Home Page",
        2 => "Soil Test Page",
        3 => "Crop Calendar Page",
        4 => "Drone Service Page",
        5 => "Shop Page",
        6 => "Shop Category Page",
    ],

    "banner_text" => [
        "home" => 1,
        "soil_test" => 2,
        "crop_calendar" => 3,
        "drone_service" => 4,
        "shop_banner" => 5,
        "shop_category_banner" => 6,
    ],

    "enable_modules" => env("ENABLE_MODULES", ""),

    "goto_page" => [
        "home"=>"Home",
        "pop"=>"POP",
        "farm"=>"Farm",
        "product_category"=>"Product Category",
        "soil_test" => "Soil Test",
        "shop" => "Shop",
        "order" => "Order",
        "crop_practices" => "Crop Practices",
        "crop_advisory" => "Crop Advisory",
        "crop_care" => "Crop Care",
        "community" => "Community",
        "video" => "Video",
        "news" => "News",
        "blog" => "Blog",
        "weather" => "Weather",
        "market_price" => "Market Price",
        "drone" => "Drone",
        "offer" => "Offer",
        "offer_details" => "Offer Details",
        "product_detail" => "Product Detail",
        "plan" => "Plan",
        "manufacture" => "Manufacture",
        "shop_banner" => "Shop Banner",
        "shop_category_banner" => "Shop Category Banner"
    ], 
    "user_soil_test_unit" => [
        "kg/ac",
        "gram/plant",
    ],
    "sample_product" => "default/600x600.jpg",
    "billing_status"=>[
        "PENDING",
      ],
    "dashboard_access_ffc" => [
        '925654','435400','711022'
    ],
    "special_offers_default_amount" => '0.00' ,

    "cancel_reason" => [
        "Not Interested",
        // "Delay in Delivery",
        "Ordered by Mistake",
        "Test Order",
        "Need to Change Shipping Address",
        "Repeat Order",
        "Shipping Cost Too High",
        "Item Price Too High",
        "Found Cheaper Somewhere Else"
    ], 

    "order_track_status" => [
        "Order Placed",
        "Order confirmed",
        "Shipped",
        "In transit",
        "Out for delivery",
        "Delivered",
    ], 
];
